### ISSUE TITLE
Problems loading the config file + rendeting fenced code blocks

### ISSUE THREAD

**Issue by yuigoto** [Fizzadar/Luapress#56]
I'm totally a beginner in both Lua + Luapress, so I'm kinda doubting I did the right thing here or not.

The config files weren't being properly loaded on Windows 10 here, so I ended up modifying the "luapress" bin file on my fork, like the one I'm attaching here (see lines 127~129). Would it be ok, if this was the right thing to do, to create a pull request? :P

[luapress.zip](https://github.com/Fizzadar/Luapress/files/1275674/luapress.zip)

Also, I kinda have a small problem rendering fenced code blocks, could this be related to something in `markdown.lua`?

![fenced-block](https://user-images.githubusercontent.com/346572/30040715-74a78638-91b9-11e7-8fb6-9a20497252c8.png)

**Comment by Fizzadar** [comment]
@yuigoto a PR would be good, yes! What was the error you were seeing?

The fenced code is because it's not actually part of the original markdown spec - however I've just pushed a change that makes these work in https://github.com/Fizzadar/Luapress/commit/39756f2b85d7382c792b7c4e5d1bfd8b2f9479d9, which I'm hoping to release in `v3.5` by the end of the year :)

**Comment by Fizzadar** [comment]
Super delayed but I've finally released `v3.5` which supports fenced code blocks!
